// Copyright 2026 ConductorOne, Inc.
// SPDX-License-Identifier: Apache-2.0

package astaudit

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Options are the audit's inputs. All three are explicit: none defaults to the
// working directory, because a root that quietly became "wherever this was run
// from" is exactly the way a count stops being about the thing it names.
type Options struct {
	// SourceRoot is the source backend/ directory. Twenty-nine of the
	// thirty rows are derived from it.
	SourceRoot string
	// TargetRoot is the AppHub repository root. Exactly one row -- E28, the
	// count of import-boundary rules -- is a claim about the target rather than
	// the source, and cannot be derived from SourceRoot at all. Requiring it
	// rather than exempting the row is what keeps the row set complete by
	// construction instead of by omission.
	TargetRoot string
	// Artifact, when set, is the committed evidence-table document. With Check
	// false it is written; with Check true it is byte-compared against freshly
	// generated output and any difference is fatal.
	//
	// A byte comparison is the only check left over the document, and it is the
	// only one that has no divergence surface: there is nothing to parse, so
	// there is no grammar to be wrong about.
	Artifact string
	// Check selects comparison rather than generation.
	Check bool
	// AllowDirty permits a run over a tree with uncommitted changes. Off by
	// default: a figure counted over a working copy is not a claim about the
	// commit whose hash would otherwise be printed beside it. The override
	// exists for local iteration and is deliberately something a human types.
	AllowDirty bool
}

// Run derives every row of the evidence table and writes it to w.
//
// It returns an *IncompleteError if it could not establish something it needs:
// a population it could not traverse in full, a figure with no denominator, or a
// row of the table it did not derive. There is no partial success -- a table
// missing a row looks exactly like a correct table, which is the failure the
// row-set contract exists for.
func Run(w io.Writer, opts Options) (err error) {
	defer recoverFail(&err)

	if opts.SourceRoot == "" || opts.TargetRoot == "" {
		fail("SourceRoot and TargetRoot are both required and neither has a default")
	}

	// Resolved before anything is counted, so a run that cannot name the trees
	// it is about produces no figures at all.
	srcRev := gitRevision("source", opts.SourceRoot)
	tgtRev := gitRevision("target", opts.TargetRoot)
	srcRev.requireAttributable("source", opts.AllowDirty)
	tgtRev.requireAttributable("target", opts.AllowDirty)

	r := newRecorder(evidenceTable)

	MT := mustTree("MT", filepath.Join(opts.SourceRoot, "internal/modules"), opts.SourceRoot)
	SL := mustTree("SL", filepath.Join(opts.SourceRoot, "internal/services"), opts.SourceRoot)
	INT := mustTree("INT", filepath.Join(opts.SourceRoot, "internal"), opts.SourceRoot)
	CMDT := mustTree("CMD", filepath.Join(opts.SourceRoot, "cmd"), opts.SourceRoot)

	var doc bytes.Buffer
	fmt.Fprintf(&doc, "# USOSS-6 — source-claim evidence table\n\n")
	fmt.Fprintf(&doc, "Generated by `go run ./hack/astaudit`. **Do not edit.** Every column is\n")
	fmt.Fprintf(&doc, "produced by the program: the figures and the deriving function are derived,\n")
	fmt.Fprintf(&doc, "and the prose is carried through verbatim from the declaration in\n")
	fmt.Fprintf(&doc, "`internal/astaudit/evidence.go`. Nothing reads this file back — the only check\n")
	fmt.Fprintf(&doc, "over it is `-check`, which regenerates it and compares bytes.\n\n")
	// The source revision is recorded; the target's is deliberately not.
	//
	// This document lives in the target repository, so naming a commit of that
	// repository inside it is self-referential: committing the file changes the
	// commit, and the recorded value could never be the one a reader is looking
	// at. The honest attribution is the one that is always true -- the target is
	// the repository this file is in, at whatever commit contains it -- and it
	// needs no maintenance to stay correct.
	//
	// Both trees are still resolved and both must be clean; only one is printed.
	fmt.Fprintf(&doc, "## Trees\n\n")
	fmt.Fprintf(&doc, "Every figure below is a claim about these exact trees.\n\n")
	fmt.Fprintf(&doc, "* **source**: `%s`\n", srcRev)
	fmt.Fprintf(&doc, "* **target**: this repository, at the commit containing this file.\n")
	fmt.Fprintf(&doc, "  Its revision is deliberately not recorded here: committing this file\n")
	fmt.Fprintf(&doc, "  changes it, so any value written down would always be the previous one.\n")
	if tgtRev.dirty {
		// Not recording the target's commit must not mean concealing that the
		// tree it was counted from was not a commit at all.
		fmt.Fprintf(&doc, "  **WITH UNCOMMITTED CHANGES** when this was generated "+
			"(-allow-dirty), so E28 is not a claim about any commit.\n")
	}
	fmt.Fprintf(&doc, "\n")
	fmt.Fprintf(&doc, "## Populations\n\nAST-parsed, production files only; a walk or parse error is fatal.\n\n")
	fmt.Fprintf(&doc, "* MT — %d files under `internal/modules`\n", MT.n())
	fmt.Fprintf(&doc, "* SL — %d files under `internal/services`\n", SL.n())
	fmt.Fprintf(&doc, "* INT — %d files under `internal`\n", INT.n())
	fmt.Fprintf(&doc, "* CMD — %d files under `cmd`\n\n", CMDT.n())
	fmt.Fprintf(&doc, "## The table\n\n")

	impls := moduleImpls(MT)
	r.emit("E1", total(len(impls)))
	auditExecuteBodies(r, MT, impls)
	auditCallSites(r, INT, CMDT)
	auditSetters(r, MT, impls)
	auditImports(r, MT, SL)
	auditIcons(r, MT)
	auditProgress(r, MT)
	auditRegistry(r, MT, opts.SourceRoot)
	auditPaved(r, MT)
	auditBoundaryRules(r, opts.TargetRoot)

	r.finish()

	r.writeTable(&doc)
	details := r.writeDetails(&doc)
	fmt.Fprintf(&doc, "\n## Completion\n\nEvery one of the %d rows the evidence table declares was derived exactly\nonce, and no row was derived that the declaration does not state. %d supporting\ndetails are listed above and are not rows. Every denominator is non-zero; every\npopulation was traversed twice with identical results, containing no symlink and\nno non-regular file, and every production file in it parsed.\n",
		len(r.order), details)

	switch {
	case opts.Artifact == "":
		_, _ = w.Write(doc.Bytes())
	case opts.Check:
		checkArtifact(w, opts.Artifact, doc.Bytes())
	default:
		// 0o600: the tool writes it, the author commits it, and git records the
		// mode as 0644 regardless. A generated file needs no wider permission
		// than its generator.
		if werr := os.WriteFile(opts.Artifact, doc.Bytes(), 0o600); werr != nil {
			fail("cannot write %s: %v", opts.Artifact, werr)
		}
		// The write error is dropped deliberately: the audit's verdict is its
		// exit status, and a failed write to the caller's log must not be
		// reported as an incomplete audit, which would say something false about
		// the source.
		_, _ = fmt.Fprintf(w, "wrote %s (%d rows, %d supporting details)\n",
			opts.Artifact, len(r.order), details)
	}
	return nil
}

// checkArtifact compares a committed evidence table against freshly generated
// output, byte for byte.
//
// This is the whole of what is checked about the document, and it is deliberate.
// Four rounds were spent detecting drift between a Markdown table and the
// program, each time more cleverly, and each time a reader found a row that was
// visible when rendered and invisible to the parser. Byte equality cannot have
// that failure: there is nothing to parse, so there is no grammar to disagree
// with a renderer about.
func checkArtifact(w io.Writer, path string, want []byte) {
	// #nosec G304 -- path is the artifact the caller named on the command line;
	// reading a caller-supplied path is the whole operation being requested.
	got, rerr := os.ReadFile(path)
	if rerr != nil {
		fail("cannot read the committed evidence table (%s): %v. A run that cannot "+
			"compare against it establishes nothing about it", path, rerr)
	}
	if bytes.Equal(got, want) {
		_, _ = fmt.Fprintf(w, "%s matches the generated evidence table exactly (%d bytes).\n",
			path, len(want))
		return
	}
	gotLines, wantLines := strings.Split(string(got), "\n"), strings.Split(string(want), "\n")
	for i := 0; i < len(gotLines) || i < len(wantLines); i++ {
		g, wl := "", ""
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if i < len(wantLines) {
			wl = wantLines[i]
		}
		if g == wl {
			continue
		}
		fail("%s is stale: it differs from the generated evidence table at line %d.\n"+
			"  committed: %q\n  generated: %q\n"+
			"Regenerate it rather than editing it -- it is output, not a document",
			path, i+1, g, wl)
	}
	fail("%s differs from the generated evidence table in length (%d bytes committed, "+
		"%d generated)", path, len(got), len(want))
}

// ---------------------------------------------------------------- helpers ---

func isNilIdent(e ast.Expr) bool {
	id, ok := e.(*ast.Ident)
	return ok && id.Name == "nil"
}

func recvType(fd *ast.FuncDecl) string {
	if fd.Recv == nil || len(fd.Recv.List) == 0 {
		return ""
	}
	switch t := fd.Recv.List[0].Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

func params(fd *ast.FuncDecl) []string {
	var out []string
	for _, p := range fd.Type.Params.List {
		if len(p.Names) == 0 {
			out = append(out, "")
			continue
		}
		for _, n := range p.Names {
			out = append(out, n.Name)
		}
	}
	return out
}

func results(fd *ast.FuncDecl) int {
	if fd.Type.Results == nil {
		return 0
	}
	n := 0
	for _, res := range fd.Type.Results.List {
		c := len(res.Names)
		if c == 0 {
			c = 1
		}
		n += c
	}
	return n
}

func anyImport(f *ast.File, pred func(string) bool) bool {
	for _, im := range f.Imports {
		if pred(strings.Trim(im.Path.Value, `"`)) {
			return true
		}
	}
	return false
}

func countImporters(t tree, pred func(string) bool) int {
	n := 0
	for _, fl := range t.files {
		if anyImport(fl.f, pred) {
			n++
		}
	}
	return n
}

// referencesIdent reports whether name appears as an identifier anywhere under
// n. Used to decide whether a value is read on a path, which is a question about
// the AST rather than about types, and is stated as such on the rows that use it.
func referencesIdent(n ast.Node, name string) bool {
	if name == "" || name == "_" {
		return false
	}
	found := false
	ast.Inspect(n, func(m ast.Node) bool {
		if id, ok := m.(*ast.Ident); ok && id.Name == name {
			found = true
		}
		return !found
	})
	return found
}

// selectorCall reports whether n is a call of the form x.sel(...).
func selectorCall(n ast.Node, sel string) (*ast.CallExpr, bool) {
	ce, ok := n.(*ast.CallExpr)
	if !ok {
		return nil, false
	}
	se, ok := ce.Fun.(*ast.SelectorExpr)
	if !ok || se.Sel.Name != sel {
		return nil, false
	}
	return ce, true
}

// ------------------------------------------------------------------- E1-E5 ---

type moduleImpl struct {
	path string
	recv string
	fd   *ast.FuncDecl
}

func moduleImpls(MT tree) []moduleImpl {
	var impls []moduleImpl
	for _, fl := range MT.files {
		for _, d := range fl.f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name.Name != "Execute" || fd.Body == nil {
				continue
			}
			if len(params(fd)) == 3 && results(fd) == 2 {
				impls = append(impls, moduleImpl{fl.path, recvType(fd), fd})
			}
		}
	}
	return impls
}

func auditExecuteBodies(r *recorder, MT tree, impls []moduleImpl) {
	n := len(impls)
	var rec, disc, none, branch, selfVal, nested, bothNonNil, nonTrue, falseNilErr int
	for _, im := range impls {
		ps := params(im.fd)
		if len(ps) < 2 {
			fail("E2: %s has %d parameters; the population was built on 3", im.path, len(ps))
		}
		pname := ps[1]
		uses, discards, inCond, inComposite := 0, 0, 0, 0
		sv, ns, bn, nt, fn := false, false, false, false, false
		ast.Inspect(im.fd.Body, func(node ast.Node) bool {
			switch x := node.(type) {
			case *ast.AssignStmt:
				if len(x.Lhs) == 1 && len(x.Rhs) == 1 {
					if l, ok := x.Lhs[0].(*ast.Ident); ok && l.Name == "_" {
						if rhs, ok := x.Rhs[0].(*ast.Ident); ok && rhs.Name == pname {
							discards++
						}
					}
				}
			case *ast.IfStmt:
				if x.Cond != nil {
					ast.Inspect(x.Cond, func(m ast.Node) bool {
						if id, ok := m.(*ast.Ident); ok && id.Name == pname {
							inCond++
						}
						return true
					})
				}
			case *ast.KeyValueExpr:
				ast.Inspect(x.Value, func(m ast.Node) bool {
					if id, ok := m.(*ast.Ident); ok && id.Name == pname {
						inComposite++
					}
					return true
				})
			case *ast.Ident:
				if x.Name == pname {
					uses++
				}
			case *ast.CallExpr:
				if se, ok := x.Fun.(*ast.SelectorExpr); ok && se.Sel.Name == "Validate" {
					sv = true
				}
			case *ast.TypeAssertExpr:
				if _, ok := x.X.(*ast.IndexExpr); ok {
					switch x.Type.(type) {
					case *ast.MapType, *ast.ArrayType:
						ns = true
					}
				}
			case *ast.ReturnStmt:
				if len(x.Results) != 2 {
					return true
				}
				if !isNilIdent(x.Results[0]) && !isNilIdent(x.Results[1]) {
					bn = true
				}
				var cl *ast.CompositeLit
				switch res := x.Results[0].(type) {
				case *ast.UnaryExpr:
					cl, _ = res.X.(*ast.CompositeLit)
				case *ast.CompositeLit:
					cl = res
				}
				if cl == nil {
					return true
				}
				for _, el := range cl.Elts {
					kv, ok := el.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					if k, ok := kv.Key.(*ast.Ident); !ok || k.Name != "Success" {
						continue
					}
					if id, ok := kv.Value.(*ast.Ident); !ok || id.Name != "true" {
						nt = true
						if isNilIdent(x.Results[1]) {
							fn = true
						}
					}
				}
			}
			return true
		})
		switch {
		case uses == 0:
			none++
		case discards > 0 && uses == discards:
			disc++
		case inComposite > 0:
			rec++
		}
		if inCond > 0 {
			branch++
		}
		for _, b := range []struct {
			v bool
			c *int
		}{{sv, &selfVal}, {ns, &nested}, {bn, &bothNonNil}, {nt, &nonTrue}, {fn, &falseNilErr}} {
			if b.v {
				*b.c++
			}
		}
	}
	r.emit("E2", ratio(rec, n))
	r.emit("E3", ratio(disc, n))
	r.emit("E4", ratio(none, n))
	r.emit("E5", ratio(branch, n))
	r.emit("E14", ratio(selfVal, n))
	r.emit("E20", ratio(nested, n))
	r.emit("E21", ratio(bothNonNil, n))
	r.emit("E22a", ratio(falseNilErr, n))
	r.emit("E22b", ratio(nonTrue, n))
	_ = MT
}

// -------------------------------------------------------------- E6-E9 sites ---

// execSite is one call of the Module shape, with the operands its caller bound
// the results to. E7, E8 and E9 are claims about what the caller then does, so
// each needs the enclosing function, not just the call.
type execSite struct {
	where    string
	call     *ast.CallExpr
	fn       *ast.FuncDecl
	resIdent string
	errIdent string
}

// auditCallSites derives E6 (how many Execute calls have the Module arity) and
// the three claims about what those callers do with the results.
//
// E6's denominator is counted over whole files and the sites are collected over
// function declarations, and the two are required to agree. They can differ: a
// call in a package-level variable initialiser is in a file but in no function
// declaration. Requiring agreement turns that into a failure rather than a
// population that quietly shrank between one row and the next.
func auditCallSites(r *recorder, INT, CMDT tree) {
	three, allCalls := 0, 0
	for _, t := range []tree{INT, CMDT} {
		for _, fl := range t.files {
			ast.Inspect(fl.f, func(n ast.Node) bool {
				ce, ok := selectorCall(n, "Execute")
				if !ok {
					return true
				}
				allCalls++
				if len(ce.Args) == 3 {
					three++
				}
				return true
			})
		}
	}
	r.emit("E6", ratio(three, allCalls))

	var sites []execSite
	for _, t := range []tree{INT, CMDT} {
		for _, fl := range t.files {
			for _, d := range fl.f.Decls {
				fd, ok := d.(*ast.FuncDecl)
				if !ok || fd.Body == nil {
					continue
				}
				ast.Inspect(fd, func(n ast.Node) bool {
					ce, ok := selectorCall(n, "Execute")
					if !ok || len(ce.Args) != 3 {
						return true
					}
					sites = append(sites, execSite{where: t.pos(ce), call: ce, fn: fd})
					return true
				})
			}
		}
	}
	if len(sites) != three {
		fail("E7-E9: %d Module-arity Execute calls were found inside function "+
			"declarations but %d were found in the files; a call outside any function "+
			"declaration would be counted by E6 and then silently missing from the rows "+
			"about what its caller does", len(sites), three)
	}

	// Bind each site's result operands. A site whose results are not assigned at
	// all is a state these rows have no answer for, so it ends the run rather
	// than being dropped from a denominator it belongs in.
	for i := range sites {
		s := &sites[i]
		var lhs []ast.Expr
		ast.Inspect(s.fn, func(n ast.Node) bool {
			as, ok := n.(*ast.AssignStmt)
			if !ok {
				return true
			}
			for _, rhs := range as.Rhs {
				if rhs == s.call {
					lhs = as.Lhs
				}
			}
			return true
		})
		if len(lhs) != 2 {
			fail("E7: the Module-arity Execute call at %s does not bind its two results "+
				"to two operands (found %d); the rows about what the caller does with the "+
				"Result have no answer for that shape and the tool must be edited to "+
				"describe it", s.where, len(lhs))
		}
		name := func(e ast.Expr) string {
			if id, ok := e.(*ast.Ident); ok {
				return id.Name
			}
			return ""
		}
		s.resIdent, s.errIdent = name(lhs[0]), name(lhs[1])
		if s.errIdent == "" || s.errIdent == "_" {
			fail("E8: the Module-arity Execute call at %s binds its error to %q; a site "+
				"that does not name its error cannot be asked whether it inspects the "+
				"error's kind", s.where, s.errIdent)
		}
	}

	// E7 -- the partial Result is lost when the caller cannot read it on the
	// error path: either it was discarded outright, or no branch guarding on the
	// error being non-nil references it.
	lost, byDiscard, byBranch := 0, 0, 0
	var e7where, e9where []string
	for _, s := range sites {
		if s.resIdent == "_" {
			lost++
			byDiscard++
			e7where = append(e7where, s.where+" (discarded at the call)")
			continue
		}
		branches := errBranches(s.fn, s.errIdent)
		if len(branches) == 0 {
			fail("E7: the Module-arity Execute call at %s binds its error to %q but no "+
				"branch in the enclosing function tests %s != nil; whether a partial "+
				"Result is lost on the error path is not decidable for that shape and the "+
				"tool must be edited to describe it", s.where, s.errIdent, s.errIdent)
		}
		reads := false
		for _, b := range branches {
			if referencesIdent(b, s.resIdent) {
				reads = true
			}
		}
		if !reads {
			lost++
			byBranch++
			e7where = append(e7where, fmt.Sprintf("%s (%s never read in the %s != nil branch)",
				s.where, s.resIdent, s.errIdent))
		}
	}

	// E8 -- inspecting the error's kind, over the whole enclosing function,
	// which is the widest scope the claim could be true in.
	inspects := 0
	for _, s := range sites {
		if inspectsErrorKind(s.fn, s.errIdent) {
			inspects++
		}
	}

	// E9 -- an empty userID passed as the second argument.
	empty := 0
	for _, s := range sites {
		lit, ok := s.call.Args[1].(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			continue
		}
		v, uerr := strconv.Unquote(lit.Value)
		if uerr != nil {
			fail("E9: the userID argument at %s is a string literal this cannot unquote "+
				"(%s): %v", s.where, lit.Value, uerr)
		}
		if v == "" {
			empty++
			e9where = append(e9where, s.where)
		}
	}

	r.emit("E7", ratio(lost, len(sites)))
	r.detail("%d discard the Result at the call, %d never read it in the error branch: %s",
		byDiscard, byBranch, strings.Join(e7where, ", "))
	r.emit("E8", ratio(inspects, len(sites)))
	r.emit("E9", ratio(empty, len(sites)))
	if len(e9where) > 0 {
		r.detail("empty userID passed at: %s", strings.Join(e9where, ", "))
	}
}

// errBranches returns the bodies of every if statement in fn whose condition
// tests errName != nil. These are the paths on which the caller knows the call
// failed.
func errBranches(fn *ast.FuncDecl, errName string) []ast.Node {
	var out []ast.Node
	ast.Inspect(fn, func(n ast.Node) bool {
		is, ok := n.(*ast.IfStmt)
		if !ok || is.Cond == nil {
			return true
		}
		guards := false
		ast.Inspect(is.Cond, func(m ast.Node) bool {
			be, ok := m.(*ast.BinaryExpr)
			if !ok || be.Op != token.NEQ || !isNilIdent(be.Y) {
				return true
			}
			if id, ok := be.X.(*ast.Ident); ok && id.Name == errName {
				guards = true
			}
			return true
		})
		if guards {
			out = append(out, is.Body)
		}
		return true
	})
	return out
}

// inspectsErrorKind reports whether fn asks what kind of error errName is, by
// the only two ways the standard library offers.
func inspectsErrorKind(fn *ast.FuncDecl, errName string) bool {
	found := false
	ast.Inspect(fn, func(n ast.Node) bool {
		ce, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		se, ok := ce.Fun.(*ast.SelectorExpr)
		if !ok || (se.Sel.Name != "Is" && se.Sel.Name != "As") {
			return true
		}
		if pkg, ok := se.X.(*ast.Ident); !ok || pkg.Name != "errors" {
			return true
		}
		for _, a := range ce.Args {
			if referencesIdent(a, errName) {
				found = true
			}
		}
		return true
	})
	return found
}

// ------------------------------------------------------------- E10-E13 ---

func auditSetters(r *recorder, MT tree, impls []moduleImpl) {
	n := len(impls)
	fields := map[string]bool{}
	setters, setterRecv := 0, map[string]bool{}
	for _, fl := range MT.files {
		for _, d := range fl.f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Body == nil {
				continue
			}
			if !strings.HasPrefix(fd.Name.Name, "Set") || len(fd.Name.Name) < 4 ||
				fd.Name.Name[3] < 'A' || fd.Name.Name[3] > 'Z' {
				continue
			}
			setters++
			setterRecv[recvType(fd)] = true
			ast.Inspect(fd.Body, func(node ast.Node) bool {
				as, ok := node.(*ast.AssignStmt)
				if !ok {
					return true
				}
				for _, l := range as.Lhs {
					if se, ok := l.(*ast.SelectorExpr); ok {
						fields[se.Sel.Name] = true
					}
				}
				return true
			})
		}
	}
	r.emit("E11", total(setters))
	r.emit("E10", ratio(len(setterRecv), n))

	if len(fields) == 0 {
		fail("E12: no fields derived from %d setter bodies; the guard population would be empty",
			setters)
	}
	fnames := make([]string, 0, len(fields))
	for k := range fields {
		fnames = append(fnames, k)
	}
	sort.Strings(fnames)

	isGuardField := func(e ast.Expr) bool {
		switch x := e.(type) {
		case *ast.SelectorExpr:
			return fields[x.Sel.Name]
		case *ast.Ident:
			return fields[x.Name]
		}
		return false
	}
	guardsAll, guardsReturning := 0, 0
	for _, im := range impls {
		ast.Inspect(im.fd.Body, func(node ast.Node) bool {
			is, ok := node.(*ast.IfStmt)
			if !ok || is.Cond == nil {
				return true
			}
			g := 0
			ast.Inspect(is.Cond, func(m ast.Node) bool {
				if be, ok := m.(*ast.BinaryExpr); ok && be.Op == token.EQL &&
					isNilIdent(be.Y) && isGuardField(be.X) {
					g++
				}
				return true
			})
			if g == 0 {
				return true
			}
			guardsAll += g
			ret := false
			ast.Inspect(is.Body, func(m ast.Node) bool {
				if _, ok := m.(*ast.ReturnStmt); ok {
					ret = true
				}
				return true
			})
			if ret {
				guardsReturning += g
			}
			return true
		})
	}
	r.emit("E12", ratio(guardsReturning, guardsAll))
	r.detail("fields derived from the setter bodies: %s", strings.Join(fnames, " "))

	vTot, vHit := 0, 0
	for _, fl := range MT.files {
		for _, d := range fl.f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name.Name != "Validate" || fd.Body == nil {
				continue
			}
			vTot++
			ast.Inspect(fd.Body, func(node ast.Node) bool {
				if _, ok := selectorCall(node, "ValidateDeclaredParams"); ok {
					vHit++
				}
				return true
			})
		}
	}
	r.emit("E13", ratio(vHit, vTot))
}

// ------------------------------------------------------------- E15-E19 ---

func auditImports(r *recorder, MT, SL tree) {
	r.emit("E15", ratio(countImporters(MT, func(p string) bool {
		return strings.Contains(p, "/internal/services")
	}), MT.n()))
	r.emit("E16a", ratio(countImporters(SL, func(p string) bool {
		return strings.HasSuffix(p, "/internal/modules")
	}), SL.n()))
	r.emit("E16b", ratio(countImporters(SL, func(p string) bool {
		return strings.Contains(p, "/internal/modules")
	}), SL.n()))

	// E17 states two figures -- by file and by package -- and is one row, so the
	// two cannot drift apart into a row and a not-quite-row.
	importsDB := func(p string) bool { return strings.HasSuffix(p, "/internal/database") }
	pkgs, pkgsImporting := map[string]bool{}, map[string]bool{}
	for _, fl := range MT.files {
		d := filepath.Dir(fl.path)
		pkgs[d] = true
		if anyImport(fl.f, importsDB) {
			pkgsImporting[d] = true
		}
	}
	r.emit("E17", labelled("files", countImporters(MT, importsDB), MT.n()),
		labelled("packages", len(pkgsImporting), len(pkgs)))

	r.emit("E18", ratio(countImporters(MT, func(p string) bool {
		return strings.HasPrefix(p, "github.com/aws/aws-sdk-go-v2")
	}), MT.n()))

	goStmts := 0
	for _, fl := range MT.files {
		found := false
		ast.Inspect(fl.f, func(n ast.Node) bool {
			if _, ok := n.(*ast.GoStmt); ok {
				found = true
			}
			return true
		})
		if found {
			goStmts++
		}
	}
	r.emit("E19", ratio(goStmts, MT.n()))
}

// ----------------------------------------------------------------- E23 ---

// snakeCase is the form E23 claims of the icon arguments. E23 is a claim about
// the *form* of a string and nothing else: whether an icon name is a member of
// any icon set is not checkable from this source tree, and the row says so
// rather than implying a count it cannot make.
var snakeCase = regexp.MustCompile(`^[a-z][a-z0-9]*(_[a-z0-9]+)*$`)

func auditIcons(r *recorder, MT tree) {
	const iconArg = 3 // NewBaseModule(id, name, description, icon, category)
	pop, matching := 0, 0
	var icons []string
	for _, fl := range MT.files {
		ast.Inspect(fl.f, func(n ast.Node) bool {
			ce, ok := selectorCall(n, "NewBaseModule")
			if !ok || len(ce.Args) <= iconArg {
				return true
			}
			pop++
			lit, ok := ce.Args[iconArg].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				fail("E23: the icon argument at %s is not a string literal (%T); E23 is a "+
					"claim about the lexical form of a literal, so a computed icon is a "+
					"state the row cannot describe and the tool must be edited to say so",
					MT.pos(ce), ce.Args[iconArg])
			}
			v, uerr := strconv.Unquote(lit.Value)
			if uerr != nil {
				fail("E23: cannot unquote the icon argument at %s (%s): %v", MT.pos(ce), lit.Value, uerr)
			}
			icons = append(icons, v)
			if snakeCase.MatchString(v) {
				matching++
			}
			return true
		})
	}
	sort.Strings(icons)
	r.emit("E23", ratio(matching, pop))
	r.detail("icon arguments, lexical form only -- membership of an icon set is not "+
		"checkable here: %s", strings.Join(icons, " "))
}

// ----------------------------------------------------------------- E24 ---

func auditProgress(r *recorder, MT tree) {
	var lit, binx, ident, other, rpTotal int
	for _, fl := range MT.files {
		ast.Inspect(fl.f, func(n ast.Node) bool {
			ce, ok := selectorCall(n, "ReportProgress")
			if !ok || len(ce.Args) < 2 {
				return true
			}
			rpTotal++
			switch a := ce.Args[1].(type) {
			case *ast.BasicLit:
				if a.Kind == token.INT {
					lit++
				} else {
					other++
				}
			case *ast.BinaryExpr:
				binx++
			case *ast.Ident:
				ident++
			default:
				other++
			}
			return true
		})
	}
	if lit+binx+ident+other != rpTotal {
		fail("E24: classified %d of %d calls; the classes must partition the population",
			lit+binx+ident+other, rpTotal)
	}
	// One row, four figures. The row this whole contract was written for is
	// still one row of the table, so the emitted rows and the table's rows map
	// one-to-one without a mapping to maintain.
	r.emit("E24", labelled("integer literals", lit, rpTotal),
		labelled("arithmetic expressions", binx, rpTotal),
		labelled("identifiers", ident, rpTotal),
		labelled("anything else", other, rpTotal))
}

// ------------------------------------------------------------- E25-E26 ---

func auditRegistry(r *recorder, MT tree, sourceRoot string) {
	regAll, regDiscarded := 0, 0
	for _, fl := range MT.files {
		if filepath.Base(fl.path) != "registry.go" {
			continue
		}
		ast.Inspect(fl.f, func(n ast.Node) bool {
			if _, ok := selectorCall(n, "Register"); ok {
				regAll++
			}
			return true
		})
		ast.Inspect(fl.f, func(n ast.Node) bool {
			es, ok := n.(*ast.ExprStmt)
			if !ok {
				return true
			}
			if _, ok := selectorCall(es.X, "Register"); ok {
				regDiscarded++
			}
			return true
		})
	}
	r.emit("E25", ratio(regDiscarded, regAll))

	cmdRoot := filepath.Join(sourceRoot, "cmd")
	entries, err := os.ReadDir(cmdRoot)
	if err != nil {
		fail("E26: cannot read %s: %v", cmdRoot, err)
	}
	cmdDirs, withRegistry := 0, 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		cmdDirs++
		sub := mustTree("CMD/"+e.Name(), filepath.Join(cmdRoot, e.Name()), sourceRoot)
		found := false
		for _, fl := range sub.files {
			ast.Inspect(fl.f, func(n ast.Node) bool {
				if _, ok := selectorCall(n, "NewRegistry"); ok {
					found = true
				}
				return true
			})
		}
		if found {
			withRegistry++
		}
	}
	r.emit("E26", ratio(withRegistry, cmdDirs))
}

// ----------------------------------------------------------------- E27 ---

func auditPaved(r *recorder, MT tree) {
	modMethods := map[string]bool{
		"ID": true, "Name": true, "Description": true, "Icon": true,
		"Category": true, "Execute": true, "Validate": true, "Schema": true,
	}
	paved := map[string]bool{}
	sep := string(filepath.Separator)
	for _, fl := range MT.files {
		if !strings.Contains(fl.path, sep+"paved"+sep) {
			continue
		}
		for _, d := range fl.f.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok && fd.Recv != nil && fd.Name.IsExported() {
				paved[fd.Name.Name] = true
			}
		}
	}
	matching := 0
	pnames := make([]string, 0, len(paved))
	for k := range paved {
		pnames = append(pnames, k)
		if modMethods[k] {
			matching++
		}
	}
	sort.Strings(pnames)
	r.emit("E27", ratio(matching, len(paved)))
	r.detail("paved exported methods: %s", strings.Join(pnames, " "))
}

// ----------------------------------------------------------------- E28 ---

// auditBoundaryRules derives the one row that is a claim about the target
// repository rather than the source.
//
// E28 counts the import-boundary rules AppHub enforces. No amount of reading
// the source tree can establish it, which is why TargetRoot is a required input
// rather than E28 being exempted from the row set. An exemption is an omission
// with a note attached, and the failure this contract exists for is precisely a
// row that is absent while the table says it is derived.
func auditBoundaryRules(r *recorder, targetRoot string) {
	bt := mustTree("BOUNDARY", filepath.Join(targetRoot, "internal/boundary"), targetRoot)

	var lits []*ast.CompositeLit
	var where []string
	for _, fl := range bt.files {
		ast.Inspect(fl.f, func(n ast.Node) bool {
			kv, ok := n.(*ast.KeyValueExpr)
			if !ok {
				return true
			}
			if k, ok := kv.Key.(*ast.Ident); !ok || k.Name != "Rules" {
				return true
			}
			cl, ok := kv.Value.(*ast.CompositeLit)
			if !ok {
				return true
			}
			lits = append(lits, cl)
			where = append(where, bt.pos(cl))
			return true
		})
	}
	if len(lits) != 1 {
		fail("E28: found %d Rules composite literals under %s (%s); the row counts the "+
			"rule set this repository enforces, and it is only a count if there is exactly "+
			"one place that states it", len(lits), bt.root, strings.Join(where, ", "))
	}

	names := make([]string, 0, len(lits[0].Elts))
	for _, el := range lits[0].Elts {
		cl, ok := el.(*ast.CompositeLit)
		if !ok {
			fail("E28: rule %d in %s is not a composite literal (%T); the rule set cannot "+
				"be enumerated by name", len(names), where[0], el)
		}
		named := ""
		for _, f := range cl.Elts {
			kv, ok := f.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			if k, ok := kv.Key.(*ast.Ident); !ok || k.Name != "Name" {
				continue
			}
			lit, ok := kv.Value.(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			v, uerr := strconv.Unquote(lit.Value)
			if uerr != nil {
				fail("E28: cannot unquote a rule name in %s (%s): %v", where[0], lit.Value, uerr)
			}
			named = v
		}
		if named == "" {
			fail("E28: rule %d in %s has no string Name; an unnamed rule cannot be "+
				"reported as part of the enforced set", len(names), where[0])
		}
		names = append(names, named)
	}
	sort.Strings(names)
	r.emit("E28", total(len(names)))
	r.detail("derived from %s: %s", where[0], strings.Join(names, " "))
}
