import { Route, Routes } from 'react-router-dom'
import { Alert, Stack, Typography } from '@mui/material'
import { Layout, RequireAuth } from './components/Layout'
import { Button } from './design/Button'
import Login from './pages/Login'
import Home from './pages/Home'
import Applications from './pages/Applications'
import CreateApplication from './pages/CreateApplication'
import ApplicationDetail from './pages/ApplicationDetail'
import DeploymentDetail from './pages/DeploymentDetail'
import Vulnerabilities from './pages/Vulnerabilities'
import Authorize from './pages/Authorize'
import Settings from './pages/Settings'
import Workspace from './pages/Workspace'
import Docs from './pages/Docs'
export default function App() { return <Routes><Route path="/login" element={<Login />} /><Route element={<RequireAuth />}><Route element={<Layout />}><Route index element={<Home />} /><Route path="/applications" element={<Applications />} /><Route path="/applications/new" element={<CreateApplication />} /><Route path="/applications/:id" element={<ApplicationDetail />} /><Route path="/applications/:id/deployments/:deploymentId" element={<DeploymentDetail />} /><Route path="/vulnerabilities" element={<Vulnerabilities />} /><Route path="/authorize" element={<Authorize />} /><Route path="/settings" element={<Settings />} /><Route path="/workspace" element={<Workspace />} /><Route path="/docs" element={<Docs />} /><Route path="/docs/:slug" element={<Docs />} /><Route path="*" element={<Stack spacing={2} sx={{ p: 4 }}><Typography variant="h1">Page not found</Typography><Alert severity="info">This AppHub page does not exist.</Alert><Button to="/applications">Go to applications</Button></Stack>} /></Route></Route></Routes> }
