// Copyright 2026 ConductorOne, Inc.
// SPDX-License-Identifier: Apache-2.0

package fix

import (
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/conductorone/apphub/modules/review"
)

// maxTitleRunes bounds a pull request title. Hosts allow more; a title that
// fills a review list is unhelpful before it is invalid.
const maxTitleRunes = 120

// maxExplanationRunes bounds the agent's own words when they are forwarded to
// the requester as a failure message. It is rendered inline beside the record,
// so a long one displaces the thing it is explaining.
const maxExplanationRunes = 600

// buildCommitMessage returns the commit message.
//
// The title is one line, always. Summary is a string a model wrote and nothing
// validated it for newlines; a commit's first line is its title and everything
// after is the body, so an embedded newline silently turns one title into two
// and every tool that reads the first line reads half a sentence.
func buildCommitMessage(id Identity, p pushRequest) string {
	title := firstLine(firstNonEmpty(p.Patch.Summary, p.Finding.Title), "security fix")

	var sb strings.Builder
	fmt.Fprintf(&sb, "[%s] %s\n\n", id.Name, title)
	if p.Finding.CheckID != "" {
		fmt.Fprintf(&sb, "Finding: %s\n", firstLine(p.Finding.CheckID, ""))
	}
	if p.Finding.Title != "" && p.Finding.Title != p.Patch.Summary {
		fmt.Fprintf(&sb, "Title: %s\n", firstLine(p.Finding.Title, ""))
	}
	if p.Finding.Severity != "" {
		fmt.Fprintf(&sb, "Severity: %s\n", p.Finding.Severity)
	}
	if p.Finding.Path != "" {
		if p.Finding.Line > 0 {
			fmt.Fprintf(&sb, "Location: %s:%d\n", p.Finding.Path, p.Finding.Line)
		} else {
			fmt.Fprintf(&sb, "Location: %s\n", p.Finding.Path)
		}
	}
	fmt.Fprintf(&sb, "\nGenerated by %s for scan %s, finding %d.\n", id.Name, p.ScanID, p.Index)
	return sb.String()
}

// buildTitle returns the pull request title.
//
// The truncation counts runes, not bytes. Summary and Title are model output
// and carry whatever codepoints the model emitted; cutting at a byte offset
// splits a multi-byte rune and produces invalid UTF-8, which a hosting API
// rejects -- so the fix fails at the last step, over a character.
func buildTitle(id Identity, p pushRequest) string {
	t := firstLine(firstNonEmpty(p.Patch.Summary, p.Finding.Title, p.Finding.CheckID), "security fix")
	if utf8.RuneCountInString(t) > maxTitleRunes {
		t = string([]rune(t)[:maxTitleRunes]) + "..."
	}
	return "[" + id.Name + "] " + t
}

// buildBody returns the pull request body.
//
// Every piece of text that came from a model or from a scanner is written
// through [writeFencedBlock]. Nothing here is a special case: the finding's
// title, its detail, the verdict's reasoning and the patch summary are all
// attacker-reachable, because all four are derived from a repository this
// process does not control. Fenced, a mention is the characters "@name", a
// task list is the characters "- [ ]", and markup is markup.
//
// The fields written with %s inside backticks are the ones this module
// produced or validated: identifiers it generated, a severity from a closed
// ladder, a path that satisfied [review.SanitisePath], a category and a check
// identifier from the scanner. The last two are the weakest of them, so they
// are written inside code spans where a backtick would break out -- which is
// why they go through inlineCode rather than straight into the format string.
func buildBody(id Identity, p pushRequest, branch, commitSHA string) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "> This pull request was generated by %s's automated fix runner. **Review it before merging.**\n\n", id.Name)

	sb.WriteString("## Finding\n\n")
	if p.Finding.Title != "" {
		writeFencedBlock(&sb, p.Finding.Title)
		sb.WriteString("\n")
	}
	if p.Finding.CheckID != "" {
		fmt.Fprintf(&sb, "- check: %s\n", inlineCode(p.Finding.CheckID))
	}
	if p.Finding.Severity != "" {
		fmt.Fprintf(&sb, "- severity: %s\n", inlineCode(string(p.Finding.Severity)))
	}
	if p.Finding.Category != "" {
		fmt.Fprintf(&sb, "- category: %s\n", inlineCode(p.Finding.Category))
	}
	if p.Finding.Path != "" {
		if p.Finding.Line > 0 {
			fmt.Fprintf(&sb, "- location: %s\n", inlineCode(fmt.Sprintf("%s:%d", p.Finding.Path, p.Finding.Line)))
		} else {
			fmt.Fprintf(&sb, "- location: %s\n", inlineCode(p.Finding.Path))
		}
	}
	if p.Finding.Detail != "" {
		sb.WriteString("\n")
		writeFencedBlock(&sb, p.Finding.Detail)
	}

	sb.WriteString("\n## Verdict\n\n")
	fmt.Fprintf(&sb, "- verdict: **%s**\n", p.Verdict.Verdict)
	if p.Verdict.Reasoning != "" {
		sb.WriteString("\n")
		writeFencedBlock(&sb, p.Verdict.Reasoning)
	}

	sb.WriteString("\n## Patch summary\n\n")
	if p.Patch.Summary != "" {
		writeFencedBlock(&sb, p.Patch.Summary)
	} else {
		sb.WriteString("(none provided)\n")
	}

	sb.WriteString("\n## Provenance\n\n")
	fmt.Fprintf(&sb, "- scan: %s\n", inlineCode(p.ScanID))
	fmt.Fprintf(&sb, "- fix: %s\n", inlineCode(p.FixID))
	fmt.Fprintf(&sb, "- finding index: %s\n", inlineCode(fmt.Sprintf("%d", p.Index)))
	fmt.Fprintf(&sb, "- branch: %s\n", inlineCode(branch))
	fmt.Fprintf(&sb, "- commit: %s\n", inlineCode(commitSHA))

	fmt.Fprintf(&sb, "\n---\n\nGenerated by %s. Review before merging.\n", id.Name)
	return sb.String()
}

// writeFencedBlock writes content into a fenced block, on its own lines.
//
// The fence is sized to the content: one backtick longer than the longest run
// of backticks inside it, so text containing a fence cannot end the block
// early. A fence of a fixed length is a fence with a known escape.
//
// An empty content writes nothing, so a caller does not have to guard.
func writeFencedBlock(sb *strings.Builder, content string) {
	if content == "" {
		return
	}
	fence := pickFence(content, 3)
	sb.WriteString(fence)
	sb.WriteString("text\n")
	sb.WriteString(content)
	if !strings.HasSuffix(content, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString(fence)
	sb.WriteString("\n")
}

// inlineCode wraps s in a code span whose delimiter is sized to it, for the
// same reason [writeFencedBlock] sizes its fence.
//
// A code span whose content begins or ends with a backtick needs a space
// either side, which the renderer strips; that is added unconditionally rather
// than conditionally, because "when does this need padding" is one more rule
// to get wrong and a space inside a code span reads the same.
//
// A newline would end the span, so s is flattened first: an identifier
// spanning lines is not one this module wrote.
func inlineCode(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if s == "" {
		return "``"
	}
	delim := pickFence(s, 1)
	return delim + " " + s + " " + delim
}

// pickFence returns a run of backticks at least `least` long and strictly
// longer than the longest run in content.
func pickFence(content string, least int) string {
	longest, run := 0, 0
	for _, r := range content {
		if r == '`' {
			run++
			if run > longest {
				longest = run
			}
			continue
		}
		run = 0
	}
	n := longest + 1
	if n < least {
		n = least
	}
	return strings.Repeat("`", n)
}

// formatExplanation prepares the agent's own account of why it produced no
// patch for display beside the record.
//
// NUL bytes are removed and whitespace is collapsed: the display is a single
// line, so newlines would be lost anyway, and a control byte the agent was
// goaded into echoing has no business travelling further. The cut counts
// runes, for the same reason [buildTitle]'s does.
func formatExplanation(s string) string {
	s = strings.ReplaceAll(s, "\x00", "")
	s = strings.Join(strings.Fields(s), " ")
	if s == "" {
		return "The agent could not draft a patch for this finding"
	}
	if utf8.RuneCountInString(s) > maxExplanationRunes {
		s = string([]rune(s)[:maxExplanationRunes]) + "..."
	}
	return "The agent declined to draft a patch: " + s
}

// firstNonEmpty returns the first argument that is not blank, or "".
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

// firstLine returns the first line of s, trimmed, or fallback when that is
// empty.
func firstLine(s, fallback string) string {
	line, _, _ := strings.Cut(strings.TrimSpace(s), "\n")
	line = strings.TrimSpace(line)
	if line == "" {
		return fallback
	}
	return line
}

// pushRequest is everything the push sequence needs. It exists so the
// sequence, which is six calls deep, takes one argument rather than ten.
type pushRequest struct {
	At   Coordinates
	Tree review.Tree
	// Snapshot is the immutable commit Tree was read at. push refuses to write
	// unless the branch it is about to build on still points at it.
	Snapshot string
	Files    []FileChange
	Patch    *Patch
	Finding  review.Finding
	Verdict  *VerdictResult
	ScanID   string
	FixID    string
	Index    int64
}
